/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.SwingUtilities;

/**
 *
 * @author gh
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
        updateTimeLabel();
    }
    
    private void updateTimeLabel() {
        Timer timer = new Timer(true); // Timer runs as a daemon thread
        SimpleDateFormat formatter = new SimpleDateFormat("dd'th' MMM yyyy hh:mm a");

        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                // Get current time and format it
                String currentTime = formatter.format(new Date());
                SwingUtilities.invokeLater(() -> timelabel.setText(currentTime));
            }
        }, 0, 1000); // Update every 1 second
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageStudents = new javax.swing.JButton();
        btnManageTeachers = new javax.swing.JButton();
        btnManageClasses = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnGenerateReports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        timelabel = new javax.swing.JLabel();
        btnManageSubjects = new javax.swing.JButton();
        btnManageStudents2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LMS | Admin Panel");
        setName("Admin View"); // NOI18N
        setResizable(false);

        btnManageStudents.setText("Manage Students");

        btnManageTeachers.setText("Manage Teachers");

        btnManageClasses.setText("Manage Classes");

        btnLogout.setText("Logout");

        btnGenerateReports.setText("Reports");

        jLabel1.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");

        timelabel.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        timelabel.setForeground(new java.awt.Color(255, 255, 255));
        timelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timelabel.setText("12-01-2024 06:35AM");

        btnManageSubjects.setText("Manage Subjects");

        btnManageStudents2.setText("Class Enrollments");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageTeachers, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(btnManageStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerateReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageSubjects, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timelabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManageStudents2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(timelabel))
                .addGap(18, 18, 18)
                .addComponent(btnManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudents2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateReports, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addManageStudentsListener(ActionListener listener) {
        btnManageStudents.addActionListener(listener);
    }
    public void addManageTeachersListener(ActionListener listener) {
        btnManageTeachers.addActionListener(listener);
    }
    public void addManageClassesListener(ActionListener listener) {
        btnManageClasses.addActionListener(listener);
    }
    
    public void addManageSubjectListener(ActionListener listener) {
        btnManageSubjects.addActionListener(listener);    }
    
    public void addGenerateReportListener(ActionListener listener) {
        btnGenerateReports.addActionListener(listener);
    }
    public void addLogoutListener(ActionListener listener) {
        btnLogout.addActionListener(listener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReports;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageClasses;
    private javax.swing.JButton btnManageStudents;
    private javax.swing.JButton btnManageStudents2;
    private javax.swing.JButton btnManageSubjects;
    private javax.swing.JButton btnManageTeachers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel timelabel;
    // End of variables declaration//GEN-END:variables
}
